### ISSUE TITLE
remove duplicate tiles

### ISSUE THREAD

**Issue by PellMellKid** [hackclub/toolbox#37]

**Comment by KaiDevrim** [comment]
im in the process of removing some duplicate tiles, @karamassie is there a difference between https://hackathons.hackclub.com and https://hackclub.com/hackathons ?

**Comment by karamassie** [comment]
that is awkward, now that you're calling it out. @maxwofford the one leads to the other (the hackathons.hc being the LISTING of them). is this desired design?
