### ISSUE TITLE
500 error for zoom pro reveal code

### ISSUE THREAD

**Issue by iUnstable0** [hackclub/toolbox#48]
![image](https://github.com/hackclub/toolbox/assets/46888825/1936cb63-d00f-4d66-b74a-200009fc37e4)

https://github.com/hackclub/toolbox/assets/46888825/0c180b19-e738-4cb1-b1cc-d858d309f4cc

**Comment by opott** [comment]
I am also experiencing this issue!

**Comment by cjdenio** [comment]
(has been fixed)
